service: auxme-restapi

frameworkVersion: '2'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ca-central-1
  lambdaHashingVersion: 20201221
  environment: 
    RoomsTable: "RoomsTable"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
      Resource:
        - "arn:aws:dynamodb:ca-central-1:*:*"

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules:
      forceExclude:
        -aws-sdk

functions: ${file(serverless-configs/functions.yml)}
resources: ${file(serverless-configs/resources.yml)}