Resources:
  RoomsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
      - AttributeName: "roomId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "roomId"
        KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: RoomsTable

  UsersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
      - AttributeName: "userId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "userId"
        KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: UsersTable

  QueueTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
      - AttributeName: "queueId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "queueId"
        KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: QueueTable